___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np 

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list = [5, 10, 15, 20, 25]
my_array = np.array(my_list)
my_array

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [4]:
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [5]:
np.ones((4,4), dtype = int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [8]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [9]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [10]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [6]:
np.linspace(0,24,25, dtype = int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
np.linspace(0,25,25, dtype = int, endpoint = False).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [12]:
np.random.rand(5)

array([0.95832835, 0.65250672, 0.92635977, 0.48956945, 0.28821057])

#### 11. Create random normal distributed 5x5 array

In [10]:
x = np.random.randn(5,5)
x

array([[ 2.18474045, -0.15722536, -0.64987364, -0.67206193, -0.92311161],
       [-1.7202774 ,  0.26700864, -1.94628799, -0.64400936, -0.7015023 ],
       [ 0.07669025,  0.30939222,  0.54668056, -0.47379596,  0.67258479],
       [-1.20665975,  0.65617182,  2.07622342,  0.77295065, -0.18047955],
       [-0.60728181, -0.2801818 , -0.30165083, -0.50191319,  0.62184544]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [13]:
np.random.randint(20,50,(3,4))

array([[21, 43, 28, 26],
       [34, 34, 36, 47],
       [35, 39, 46, 26]])

#### 13. Reshape the array below with shape 6x8

In [13]:
ranarr = np.random.randint(0,60,48)
ranarr

array([17,  8, 28, 27, 29, 15, 43, 23, 40, 31, 30,  1, 41, 59, 40, 43, 11,
       53, 27, 52, 23, 43, 21, 14, 53, 14, 41, 35, 59, 39,  9, 22, 38, 36,
       33, 52, 45, 16, 34,  9,  7, 38,  7, 25, 32, 19, 18, 17])

In [14]:
ranarr.reshape(6,8)

array([[17,  8, 28, 27, 29, 15, 43, 23],
       [40, 31, 30,  1, 41, 59, 40, 43],
       [11, 53, 27, 52, 23, 43, 21, 14],
       [53, 14, 41, 35, 59, 39,  9, 22],
       [38, 36, 33, 52, 45, 16, 34,  9],
       [ 7, 38,  7, 25, 32, 19, 18, 17]])

In [15]:
ranarr.reshape(-1,8)

array([[17,  8, 28, 27, 29, 15, 43, 23],
       [40, 31, 30,  1, 41, 59, 40, 43],
       [11, 53, 27, 52, 23, 43, 21, 14],
       [53, 14, 41, 35, 59, 39,  9, 22],
       [38, 36, 33, 52, 45, 16, 34,  9],
       [ 7, 38,  7, 25, 32, 19, 18, 17]])

In [22]:
#reshape with -1


array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

In [19]:
ranarr.reshape(4,12)

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [16]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [28]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [29]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [30]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [32]:
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [18]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [33]:
mat[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [34]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [38]:
a = mat[mat<10]
a

array([1, 2, 4, 5, 6, 8, 9])

In [39]:
b = mat[mat>12]
b

array([77, 77, 77, 13, 14, 77, 16])

In [41]:
c = a + b
c

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [42]:
np.std(c)

29.700546274093877

#### 22. Get the sum of second column from array above

In [43]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [45]:
np.sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [46]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [47]:
mat[2]

array([ 9, 10, 77, 12])

In [49]:
#median
np.median(mat[2])

11.0

In [50]:
#mean
np.mean(mat[2])

27.0

In [51]:
#std
np.std(mat[2])


28.88771365130858

# Pandas Section

In [3]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [4]:
sal=pd.read_csv('Salaries.csv')

In [5]:
df = sal.head()
df

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [6]:
sal.sample(10)

Id             EmployeeName                        JobTitle  \
28754    28755           EVAN ROOSEVELT             STATIONARY ENGINEER   
32781    32782           EMILIA PATRICK                   SPECIAL NURSE   
120320  120321           Joseph Ospital              Building Inspector   
130392  130393     Richard C Greathouse  Community Police Services Aide   
122159  122160         Mario Montoya-Jr   Street Environ Svcs Oprs Supv   
63953    63954              James Bruhn                Registered Nurse   
17792    17793            ANNE HIROZAWA               EPIDEMIOLOGIST II   
28746    28747          TATIANA PADILLA                TRANSIT OPERATOR   
14993    14994          CARLOTA HILARIO       PERSONAL PROPERTY AUDITOR   
61445    61446  Maria Teresita Arradaza   Housekeeper/Food Service Clnr   

         BasePay  OvertimePay  OtherPay  Benefits   TotalPay  \
28754   23507.18         0.00    669.28       NaN   24176.46   
32781    6375.58         0.00    181.96       NaN    6557.54   
120320  94892.68      4604.45   4744.62  36615.31  104241.75   
130392  65699.02         0.00   3285.05  28939.46   68984.07   
122159  94063.01      1059.23   1532.17  34756.61   96654.41   
63953   32061.24      1227.57   2323.11  13219.87   35611.92   
17792   69000.34         0.00      0.00       NaN   69000.34   
28746   22688.48       929.62    659.77       NaN   24277.87   
14993   77581.98         0.00    480.00       NaN   78061.98   
61445   45255.43      2078.85   1151.50  26166.13   48485.78   

        TotalPayBenefits  Year  Notes         Agency  Status  
28754           24176.46  2011    NaN  San Francisco     NaN  
32781            6557.54  2011    NaN  San Francisco     NaN  
120320         140857.06  2014    NaN  San Francisco     NaN  
130392          97923.53  2014    NaN  San Francisco     NaN  
122159         131411.02  2014    NaN  San Francisco     NaN  
63953           48831.79  2012    NaN  San Francisco     NaN  
17792           69000.34  2011    NaN  San Francisco     NaN  
28746           24277.87  2011    NaN  San Francisco     NaN  
14993           78061.98  2011    NaN  San Francisco     NaN  
61445           74651.91  2012    NaN  San Francisco     NaN

In [7]:
df = sal.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [8]:
df = sal.describe()
df

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [9]:
sal.describe().T

count          mean           std      min        25%  \
Id                148654.0  74327.500000  42912.857795     1.00  37164.250   
BasePay           148045.0  66325.448841  42764.635495  -166.01  33588.200   
OvertimePay       148650.0   5066.059886  11454.380559    -0.01      0.000   
OtherPay          148650.0   3648.767297   8056.601866 -7058.59      0.000   
Benefits          112491.0  25007.893151  15402.215858   -33.89  11535.395   
TotalPay          148654.0  74768.321972  50517.005274  -618.13  36168.995   
TotalPayBenefits  148654.0  93692.554811  62793.533483  -618.13  44065.650   
Year              148654.0   2012.522643      1.117538  2011.00   2012.000   
Notes                  0.0           NaN           NaN      NaN        NaN   
Status                 0.0           NaN           NaN      NaN        NaN   

                       50%         75%        max  
Id                74327.50  111490.750  148654.00  
BasePay           65007.45   94691.050  319275.01  
OvertimePay           0.00    4658.175  245131.88  
OtherPay            811.27    4236.065  400184.25  
Benefits          28628.62   35566.855   96570.66  
TotalPay          71426.61  105839.135  567595.43  
TotalPayBenefits  92404.09  132876.450  567595.43  
Year               2013.00    2014.000    2014.00  
Notes                  NaN         NaN        NaN  
Status                 NaN         NaN        NaN

**How many different year value are there**

In [85]:
df = sal['Year'].value_counts()
df



2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [23]:
sal.Year.value_counts(dropna=False)

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [24]:
sal.Year.value_counts(dropna=False).nunique()

4

In [25]:
sal.Year.nunique()

4

**Print out max and avg Totalpay**

In [89]:
#max
max_sal = sal['TotalPay'].max()
max_sal

# sal.TotalPay.max()

567595.43

In [88]:
#avg
avg = sal['TotalPay'].mean()
avg

#sal.TotalPay.mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [105]:
len(sal[sal['TotalPay'] > avg])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [114]:
sal[sal['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [26]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [120]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

**What are the unique Jobs in dataset?**

In [122]:
sal['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [31]:
sal['JobTitle'].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [10]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.mean()) & (sal.Year == 2012)]

Id        EmployeeName                      JobTitle    BasePay  \
36159  36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160  36161        Gregory Suhr               Chief of Police  302578.00   
36161  36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162  36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163  36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...      ...                 ...                           ...        ...   
56520  56521        Sue Madrigal     Senior Eligibility Worker   63841.94   
56521  56522   Concepcion Gruber                   Secretary 2   61996.06   
56522  56523         Kerman Chan       Parking Control Officer   55358.50   
56523  56524      Ramon Lafuente       Parking Control Officer   56006.80   
56524  56525      Lai Ping Szeto            Eligibility Worker   61253.05   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
56520         0.00    568.66  29305.51   64410.60          93716.11  2012   
56521      1111.50    624.00  29981.74   63731.56          93713.30  2012   
56522      8539.77   1231.25  28579.83   65129.52          93709.35  2012   
56523      6326.45   2175.24  29192.61   64508.49          93701.10  2012   
56524       988.54   1460.00  29996.77   63701.59          93698.36  2012   

       Notes         Agency  Status  
36159    NaN  San Francisco     NaN  
36160    NaN  San Francisco     NaN  
36161    NaN  San Francisco     NaN  
36162    NaN  San Francisco     NaN  
36163    NaN  San Francisco     NaN  
...      ...            ...     ...  
56520    NaN  San Francisco     NaN  
56521    NaN  San Francisco     NaN  
56522    NaN  San Francisco     NaN  
56523    NaN  San Francisco     NaN  
56524    NaN  San Francisco     NaN  

[20366 rows x 13 columns]

In [69]:
[sal.TotalPayBenefits > sal.TotalPayBenefits.mean() & (sal.Year == 2012)]

20366

In [153]:
sum(sal[sal['Year']==2012]['TotalPay'] > avg)

16716

**How many people have the word Manager in their job title?**

In [71]:
#use apply function here


4110

In [34]:

def manager_func(x):
    if 'manager' in x.lower():
        return True
    else:
        return False


In [35]:
sal[sal.JobTitle.apply(lambda x : manager_func(x))]

Id          EmployeeName  \
0            1        NATHANIEL FORD   
83          84        EDWARD REISKIN   
87          88           KEVIN BARRY   
95          96          MIVIC HIROSE   
162        163         JULIE LABONTE   
...        ...                   ...   
147216  147217  Steven D Koneffklatt   
147502  147503    Alice B Villagomez   
147805  147806    Stephen C Laplante   
148150  148151      Shirley M Parker   
148475  148476         James P Horan   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
83      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  230827.12   
87                                         MANAGER VII   96814.36   
95                                        MANAGER VIII  215180.76   
162                                       MANAGER VIII  207501.20   
...                                                ...        ...   
147216                                     Manager III       0.00   
147502                                      Manager IV    1660.00   
147805                                      Manager II       0.00   
148150                           Real Property Manager       0.00   
148475                                      Manager IV     175.75   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0               0.0  400184.25       NaN  567595.43         567595.43  2011   
83              0.0       0.00       NaN  230827.12         230827.12  2011   
87              0.0  133563.47       NaN  230377.83         230377.83  2011   
95              0.0   12000.00       NaN  227180.76         227180.76  2011   
162             0.0    2903.37       NaN  210404.57         210404.57  2011   
...             ...        ...       ...        ...               ...   ...   
147216          0.0    1890.72    342.03    1890.72           2232.75  2014   
147502          0.0       0.00     16.60    1660.00           1676.60  2014   
147805          0.0     982.62    177.76     982.62           1160.38  2014   
148150          0.0     647.76      0.00     647.76            647.76  2014   
148475          0.0       0.00      1.41     175.75            177.16  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
83        NaN  San Francisco     NaN  
87        NaN  San Francisco     NaN  
95        NaN  San Francisco     NaN  
162       NaN  San Francisco     NaN  
...       ...            ...     ...  
147216    NaN  San Francisco     NaN  
147502    NaN  San Francisco     NaN  
147805    NaN  San Francisco     NaN  
148150    NaN  San Francisco     NaN  
148475    NaN  San Francisco     NaN  

[4110 rows x 13 columns]

In [36]:
len(sal[sal.JobTitle.apply(lambda x : manager_func(x))])

4110

In [37]:
len(sal[sal.JobTitle.apply(lambda x: True if 'manager' in x.lower() else False)])

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [38]:
sal.head(1)

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18          0.0  400184.25       NaN  567595.43         567595.43   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN

In [186]:
sal_new= sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [41]:
sal_new = sal.loc[:,'EmployeeName':'TotalPay']
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  
0       167411.18         0.00  400184.25       NaN  567595.43  
1       155966.02    245131.88  137811.38       NaN  538909.28  
2       212739.13    106088.18   16452.60       NaN  335279.91  
3        77916.00     56120.71  198306.90       NaN  332343.61  
4       134401.60      9737.00  182234.59       NaN  326373.19  
...           ...          ...        ...       ...        ...  
148649       0.00         0.00       0.00       0.0       0.00  
148650        NaN          NaN        NaN       NaN       0.00  
148651        NaN          NaN        NaN       NaN       0.00  
148652        NaN          NaN        NaN       NaN       0.00  
148653       0.00         0.00    -618.13       0.0    -618.13  

[148654 rows x 7 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [17]:
tot_min = sal.TotalPayBenefits.min()
tot_min

-618.13

In [18]:
tot_mean = sal.TotalPayBenefits.mean()
tot_mean

93692.55481056834

In [23]:
sal[(sal['TotalPayBenefits'] > tot_min) & ((sal['TotalPayBenefits'] < tot_mean))]['EmployeeName']

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object